### ISSUE TITLE
Stock: Failed to safe the stock

### ISSUE THREAD

**Issue by martinskalicky** [recursivetree/seat-inventory#1]
When adding a stock from fittings (plugin installed) I do received **"Stock: Failed to safe the stock"**. I was not able to add stock and went debug. If there is special character in fit name, its crashing.

**Steps to Reproduce:**
1) Click +Stocks
2) Select Fit with name "ʥ_debug_fit" (u have to create him before in seat-fittings plugin)
3) Select location (any)
4) Click Save

When u rename your fits so they do not use special character it works well. However we had this use case and because of that we went into this issue.

Would it be possible to solve it?

**Comment by recursivetree** [comment]
Sure, I'll investigate the issue

**Comment by recursivetree** [comment]
I prepared a fix, it will come with the next release

**Comment by martinskalicky** [comment]
Any ETA for next release?

**Comment by recursivetree** [comment]
It will probably take a while, since I'm working on adding a few major features. If you need it really urgent, I can release the fix alone.
