### ISSUE TITLE
Suggestion : Add item tracking

### ISSUE THREAD

**Issue by dstevens79** [recursivetree/seat-inventory#2]
Allowing individual item tracking at a station would allow this to be used to actually track inventory levels for industry and not just ship stocks at stations.

Basically the same thing it does now - just allow tracking of custom items in groups at specific selected stations (and possibly specific corp hangars) instead of just doctrine ships.

Also if you can track what the seat alliance industry plugin has out to be done vs a check for existing materials at the given location as required missing materials at a station this would extend the usefulness of this plugin for industry

**Comment by recursivetree** [comment]
What prevents you from creating a stock that just contains a single item instead of a whole ship?

**Comment by recursivetree** [comment]
I don't quite get what you mean by your sentence about seat alliance industry. Just so you know, there is an option to add the items from seat-alliance-industry into seat-inventory, so that items that are promised to be delivered don't appear as missing.

**Comment by dstevens79** [comment]
nope im a blind person who didnt see how to do that 👍 
I did figure it out after you posted back, thank you v. much :)
